### ISSUE TITLE
Chrome DevTools Protocol events extraction not fully "chrome-har" compatible

### ISSUE THREAD

**Issue by vroumvroum** [Everettss/puppeteer-har#1]
Please refers to https://github.com/sitespeedio/chrome-har/issues/15 for details on the issue

**Comment by LLLLLamHo** [comment]
I have the same problem. When can I solve it?

**Comment by vlad4800** [comment]
Any updates on this issue?

**Comment by Everettss** [comment]
@vroumvroum I wasn't able to reproduce your problem. As you can see this library is a simple extension to extract events for `chrome-har`, and I'm not capable of solving issue mentioned by @tobli in https://github.com/sitespeedio/chrome-har/issues/15#issuecomment-379451268. If you find some solution for this problem I'm welcome. Meanwhile, I've bumped `chrome-har` version in this package.

**Comment by rriemann** [comment]
Waiting for the merge! Thx @tai :+1:
