### ISSUE TITLE
Improve HAR compatibility with browser dev tools

### ISSUE THREAD

**Issue by rriemann-eu** [Everettss/puppeteer-har#11]
Dear Michał,

thank you for providing puppeteer-har. The European Data Protection Supervisor uses this in its [free software tool](https://github.com/EU-EDPS/website-evidence-collector) to help website developers and data protection professional to detect data protection compliance issues.

In the past, I have used a fork of your code to include a patched version from chrome-har, which ensures that HARs can be opened within Chrome/Chromium. However, the fix https://github.com/sitespeedio/chrome-har/pull/44 has now been integrated and released as [v0.11.3](https://github.com/sitespeedio/chrome-har/releases/tag/v0.11.3).

Can you please update the dependency of puppeteer-har and release a new version, so I can fix https://github.com/EU-EDPS/website-evidence-collector/issues/9 ?

**Comment by Everettss** [comment]
Closed by bumping chrome-har to version 0.11.3 https://github.com/Everettss/puppeteer-har/commit/22da3a82c377fddbe04534418de389b5b987a241

**Comment by rriemann-eu** [comment]
Thank you so much for your quick reaction! 💙
