### ISSUE TITLE
Add response body to har based on flag

### ISSUE THREAD

**Issue by rvbyron** [Everettss/puppeteer-har#8]
`chrome-har` now [supports returning response body](https://github.com/sitespeedio/chrome-har/pull/41) as part of har. This option defaults to false in `chrome-har`. Can you add support to return response body via puppeteer-har?

**Comment by phongiswindy** [comment]
While waiting for @Everettss to implement it, you may want add the response body to the har by following this revised version of @Everettss's original code: https://github.com/sitespeedio/chrome-har/pull/41#issuecomment-456913596

**Comment by PsychoXIVI** [comment]
@Everettss, this should be closed because of #10 has been accepted and merged.
